// <auto-generated />
using System;
using DiaryDSR;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DSRDiaryAPI.Migrations
{
    [DbContext(typeof(AppPostgreContext))]
    [Migration("20230726200239_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiaryDSR.Models.DiaryTask", b =>
                {
                    b.Property<int>("Taskid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Taskid"));

                    b.Property<DateTime>("Endtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Repeat")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Starttime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Taskcomment")
                        .HasColumnType("text");

                    b.Property<string>("Taskname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Taskid");

                    b.ToTable("DiaryTask");
                });

            modelBuilder.Entity("DiaryDSR.Models.TaskType", b =>
                {
                    b.Property<int>("Typeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Typeid"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Typename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Typeid");

                    b.ToTable("TaskTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
