// <auto-generated />
using System;
using DiaryDSR;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiaryDSR.Migrations
{
    [DbContext(typeof(AppPostgreContext))]
    partial class AppPostgreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiaryDSR.Models.DiaryTask", b =>
                {
                    b.Property<int>("Taskid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Taskid"));

                    b.Property<DateTime>("Endtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("Repeat")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Starttime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Taskcomment")
                        .HasColumnType("text");

                    b.Property<int>("Typeid")
                        .HasColumnType("integer");

                    b.HasKey("Taskid");

                    b.HasIndex("Typeid");

                    b.ToTable("DiaryTask");
                });

            modelBuilder.Entity("DiaryDSR.Models.TaskType", b =>
                {
                    b.Property<int>("Typeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Typeid"));

                    b.Property<string>("Typename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Typeid");

                    b.ToTable("TaskTypes");
                });

            modelBuilder.Entity("DiaryDSR.Models.DiaryTask", b =>
                {
                    b.HasOne("DiaryDSR.Models.TaskType", "Type")
                        .WithMany()
                        .HasForeignKey("Typeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DiaryDSR.Models.TaskType", b =>
                {
                    b.OwnsOne("DiaryDSR.Models.TypeColor", "Color", b1 =>
                        {
                            b1.Property<int>("TaskTypeTypeid")
                                .HasColumnType("integer");

                            b1.Property<int>("Blue")
                                .HasColumnType("integer");

                            b1.Property<int>("Green")
                                .HasColumnType("integer");

                            b1.Property<int>("Red")
                                .HasColumnType("integer");

                            b1.HasKey("TaskTypeTypeid");

                            b1.ToTable("TaskTypes");

                            b1.WithOwner()
                                .HasForeignKey("TaskTypeTypeid");
                        });

                    b.Navigation("Color")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
